### ISSUE TITLE
noarch build has failed

### ISSUE THREAD

**Issue by apcamargo** [conda-forge/version_information-feedstock#3]
It seems that the noarch build of this package has failed, so it can't be installed in Python 3.7.

**Comment by moorepants** [comment]
Thanks, the CI just needs to be rerun. I don't seem to have permissions to do so though.

**Comment by moorepants** [comment]
It is rerunning and hopefully will pass. It just had an internet timeout issue before.

**Comment by moorepants** [comment]
Fixed in #4 the circleci credentials needed updating.
